-- 1]What are the names of the players whose salary is greater than 100,000?
-- SELECT player_name FROM players
-- WHERE salary > 100000;
---------------------------------------------------------------------------
-- 2]What is the team name of the player with player_id = 3?
-- select team_name from teams
-- join players on players.team_id = teams.team_id
-- where player_id = 3;
------------------------------------------------------------------------------
-- 3]What is the total number of players in each team?
-- select count(player_id) as total_players, team_name from teams
-- join players on players.team_id = teams.team_id
-- group by teams.team_name;
------------------------------------------------------------------------------------
-- 4]What is the team name and captain name of the team with team_id = 2?
-- select team_name, captain_id, player_name from teams
-- join players on players.team_id = teams.team_id
-- where teams.team_id = 2;
----------------------------------------------------------------------------------
-- 5]What are the player names and their roles in the team with team_id = 1?
-- select player_name, role from players
-- join teams on players.team_id = teams.team_id
-- where teams.team_id = 1;
--------------------------------------------------------------------------------------
 -- 6]What are the team names and the number of matches they have won?
  --  select team_name, count(*) as number_of_wins from teams
--    join matches on teams.team_id = matches.winner_id
--    group by winner_id
--    order by number_of_wins;
---------------------------------------------------------------------------------------
-- 7]What is the average salary of players in the teams with country 'USA'?
-- select avg(salary), player_name, country from players
-- join teams on players.team_id = teams.team_id
-- where country = 'USA';
-----------------------------------------------------------------------------
-- 8]Which team won the most matches?
  -- select team_name, count(winner_id) as number_of_wins from teams
--   join matches on teams.team_id = matches.winner_id
--   group by winner_id
--   order by number_of_wins desc limit 1;
  ----------------------------------------------------------------
-- 9]What are the team names and the number of players in each team whose salary is greater than 100,000?
 -- select team_name, count(*) as players_having_salary_greter_than_100000  from teams
--  join players on teams.team_id = players.team_id
--  where salary > 100000
--  group by team_name;
  ------------------------------------------------------------------------------------
  -- 10]What is the date and the score of the match with match_id = 3?
  -- select match_date, concat(score_team1, ':' ,score_team2) as score from matches
--   where match_id = 3;
  ------------------------------------------------------------------------
  